package com.sravan.efactorapp.Event;

public enum EventType {
    USER_SIGNIN,
    USER_SIGNOUT,
    GATEWAY_FOUND_NEW,
    GATEWAY_UPDATE,
    CLOUD_GATEWAY_SHADOW_UPDATED,
    CLOUD_GATEWAY_SHADOW_UPDATED_FAILED,
    CLOUD_CONNECTING,
    CLOUD_CONNECTED,
    CLOUD_DISCONNECTED,
    CLOUD_GATEWAY_DATA_RECEIVED,
    CLOUD_DEVICE_DATA_RECEIVED,
    LOCAL_DEVICE_DATA_RECEIVED,
    DEVICE_DATA_UPDATED,
    DEVICE_COMMAND_SEND_FAILED,
    BLE_CONNECTED,
    BLE_DISCONNECTED,
    BLE_READ_DATA,
    BLE_NOTIFICATION,
    BLE_WRITTEN
}
